// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC5HUGzXOmPV9jdlFImNXiy5XpvKHartI',
    appId: '1:357880231345:web:b6f9c49d389e7ac545b990',
    messagingSenderId: '357880231345',
    projectId: 'agrimart-1b79d',
    authDomain: 'agrimart-1b79d.firebaseapp.com',
    storageBucket: 'agrimart-1b79d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Itca4O8wiNNN2EodlnQVeOsL_Bz-QYE',
    appId: '1:357880231345:android:d15998f5430fe42f45b990',
    messagingSenderId: '357880231345',
    projectId: 'agrimart-1b79d',
    storageBucket: 'agrimart-1b79d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOnEF3Uq-9Xx8-ZuKk2lfEk09JvC-mBGQ',
    appId: '1:357880231345:ios:2383796f9b88321945b990',
    messagingSenderId: '357880231345',
    projectId: 'agrimart-1b79d',
    storageBucket: 'agrimart-1b79d.firebasestorage.app',
    iosBundleId: 'com.example.agriMart',
  );
}
